(define (problem BYENG) (:domain RADAR)

(:objects 
 policeChief - police
 firechief - fire
 medichief - medic
 transportchief - transport
 apachestation courtstation substation - policestation
 adminfire mesafire scottsfire phxfire - firestation
 lukes joseph - hospital
 lake mill marketplace rural byeng - pois

)

(:init

(not_needed_diverted_traffic marketplace mill)
(=(duration_deploy_small_engines) 2)
(not_needed_attend_casualties mill )
(has_big_engines_number mesafire)
(not_needed_diverted_traffic lake marketplace)
(has_bulldozers_number mesafire)
(has_small_engines_number phxfire)
(=(duration_block_road) 2)
(not_needed_diverted_traffic byeng rural)
(=(duration_barricade) 1)
(=(duration_search_casualties) 3)

(not_needed_diverted_traffic rural rural)
(not_needed_diverted_traffic rural mill)
(has_helicopters_number adminfire)
(not_needed_attend_casualties byeng )
(not_needed_diverted_traffic mill rural)
(not_needed_diverted_traffic byeng lake)
(has_helicopters_number mesafire)
(not_needed_diverted_traffic rural byeng)
(has_bulldozers_number adminfire)
(not_needed_diverted_traffic mill mill)
(has_big_engines_number scottsfire)
(not_needed_search_casualties marketplace )
(has_helicopters_number phxfire)
(not_needed_diverted_traffic lake rural)
(not_needed_diverted_traffic byeng mill)
(has_ambulances_number lukes)
(not_needed_attend_casualties rural )
(not_needed_diverted_traffic marketplace marketplace)
(has_ladders_number adminfire)
(has_policemen_number apachestation)
(not_needed_diverted_traffic lake byeng)
(=(duration_deploy_helicopters) 3)
(not_needed_active_local_alert medichief )
(=(duration_issue_local_alert) 1)
(not_needed_search_casualties lake )
(has_police_car_number courtstation)
(has_small_engines_number mesafire)
(=(duration_attend_casualties) 3)
(has_policemen_number substation)
(has_big_engines_number adminfire)
(has_police_car_number substation)
(not_needed_active_local_alert firechief )
(has_bulldozers_number phxfire)
(has_police_car_number apachestation)
(has_ambulances_number joseph)
(=(duration_deploy_police_cars) 1)
(has_rescuers_number mesafire)
(not_needed_diverted_traffic byeng marketplace)
(=(duration_prepare_evacuation) 1)
(=(duration_deploy_rescuers) 3)
(has_policemen_number courtstation)
(=(total-cost) 0.0)
(has_ladders_number scottsfire)
(=(duration_evacuation) 5)
(=(duration_deploy_ambulances) 2)
(not_needed_diverted_traffic byeng byeng)
(has_helicopters_number scottsfire)
(not_needed_diverted_traffic rural marketplace)
(not_needed_diverted_traffic lake mill)
(has_rescuers_number phxfire)
(not_needed_diverted_traffic marketplace lake)
(not_needed_address_media )
(not_needed_diverted_traffic mill lake)
(not_needed_attend_casualties lake )
(=(duration_deploy_big_engines) 4)
(=(duration_extinguish_small_fire) 1)
(has_bulldozers_number scottsfire)
(has_ladders_number mesafire)
(not_needed_attend_casualties marketplace )
(=(duration_deploy_ladders) 3)
(not_needed_diverted_traffic rural lake)
(has_ladders_number phxfire)
(not_needed_diverted_traffic mill marketplace)
(has_rescuers_number adminfire)
(not_needed_active_local_alert transportchief )
(=(duration_position_policemen) 1)
(=(duration_set_up_helpline) 1)
(=(duration_deploy_bulldozers) 3)
(not_needed_search_casualties rural )
(not_needed_diverted_traffic marketplace rural)
(not_needed_search_casualties byeng )
(has_big_engines_number phxfire)
(=(duration_contact_media) 1)
(not_needed_search_casualties mill )
(not_needed_diverted_traffic marketplace byeng)
(not_needed_active_local_alert policeChief )
(has_small_engines_number adminfire)
(fire_at byeng)
(=(duration_address_media) 2)
(has_rescuers_number scottsfire)
(not_needed_diverted_traffic lake lake)
(has_small_engines_number scottsfire)
(not_needed_diverted_traffic mill byeng)
(=(duration_unit_actions) 1)
(=(duration_extinguish_big_fire) 1)

)

(:goal
(and
))

(:metric minimize (total-cost))
(extinguished_fire byeng)
(addressed_media)
))

(:metric minimize (total-cost))

)
